// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file headerTypeObject.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "Communication/PacketTypes/header.h"
#include "Communication/PacketTypes/headerTypeObject.h"
#include <utility>
#include <sstream>
#include <fastrtps/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>
#include <fastrtps/types/TypeObjectFactory.h>
#include <fastrtps/types/TypeNamesGenerator.h>
#include <fastrtps/types/AnnotationParameterValue.h>
#include <fastcdr/FastBuffer.h>
#include <fastcdr/Cdr.h>

using namespace eprosima::fastrtps::rtps;

void registerheaderTypes()
{
    TypeObjectFactory *factory = TypeObjectFactory::get_instance();
    factory->add_type_object("Header", GetHeaderIdentifier(true),
    GetHeaderObject(true));
    factory->add_type_object("Header", GetHeaderIdentifier(false),
    GetHeaderObject(false));

}

const TypeIdentifier* GetHeaderIdentifier(bool complete)
{
    const TypeIdentifier * c_identifier = TypeObjectFactory::get_instance()->get_type_identifier("Header", complete);
    if (c_identifier != nullptr && (!complete || c_identifier->_d() == EK_COMPLETE))
    {
        return c_identifier;
    }

    GetHeaderObject(complete); // Generated inside
    return TypeObjectFactory::get_instance()->get_type_identifier("Header", complete);
}

const TypeObject* GetHeaderObject(bool complete)
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("Header", complete);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }
    else if (complete)
    {
        return GetCompleteHeaderObject();
    }
    //else
    return GetMinimalHeaderObject();
}

const TypeObject* GetMinimalHeaderObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("Header", false);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_MINIMAL);
    type_object->minimal()._d(TK_STRUCTURE);

    type_object->minimal().struct_type().struct_flags().IS_FINAL(false);
    type_object->minimal().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_NESTED(false);
    type_object->minimal().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    MinimalStructMember mst_id;
    mst_id.common().member_id(memberId++);
    mst_id.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_id.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_id.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_id.common().member_flags().IS_OPTIONAL(false);
    mst_id.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_id.common().member_flags().IS_KEY(false);
    mst_id.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_id.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("uint32_t", false));

    MD5 id_hash("id");
    for(int i = 0; i < 4; ++i)
    {
        mst_id.detail().name_hash()[i] = id_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_id);

    MinimalStructMember mst_timeRec;
    mst_timeRec.common().member_id(memberId++);
    mst_timeRec.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_timeRec.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_timeRec.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_timeRec.common().member_flags().IS_OPTIONAL(false);
    mst_timeRec.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_timeRec.common().member_flags().IS_KEY(false);
    mst_timeRec.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_timeRec.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("int64_t", false));

    MD5 timeRec_hash("timeRec");
    for(int i = 0; i < 4; ++i)
    {
        mst_timeRec.detail().name_hash()[i] = timeRec_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_timeRec);

    MinimalStructMember mst_timeSent;
    mst_timeSent.common().member_id(memberId++);
    mst_timeSent.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_timeSent.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_timeSent.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_timeSent.common().member_flags().IS_OPTIONAL(false);
    mst_timeSent.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_timeSent.common().member_flags().IS_KEY(false);
    mst_timeSent.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_timeSent.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("int64_t", false));

    MD5 timeSent_hash("timeSent");
    for(int i = 0; i < 4; ++i)
    {
        mst_timeSent.detail().name_hash()[i] = timeSent_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_timeSent);


    // Header
    // TODO Inheritance
    //type_object->minimal().struct_type().header().base_type()._d(EK_MINIMAL);
    //type_object->minimal().struct_type().header().base_type().equivalence_hash()[0..13];

    TypeIdentifier identifier;
    identifier._d(EK_MINIMAL);

    SerializedPayload_t payload(static_cast<uint32_t>(
        MinimalStructType::getCdrSerializedSize(type_object->minimal().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("Header", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("Header", false);
}

const TypeObject* GetCompleteHeaderObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("Header", true);
    if (c_type_object != nullptr && c_type_object->_d() == EK_COMPLETE)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_COMPLETE);
    type_object->complete()._d(TK_STRUCTURE);

    type_object->complete().struct_type().struct_flags().IS_FINAL(false);
    type_object->complete().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->complete().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->complete().struct_type().struct_flags().IS_NESTED(false);
    type_object->complete().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    CompleteStructMember cst_id;
    cst_id.common().member_id(memberId++);
    cst_id.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_id.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_id.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_id.common().member_flags().IS_OPTIONAL(false);
    cst_id.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_id.common().member_flags().IS_KEY(false);
    cst_id.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_id.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("uint32_t", false));

    cst_id.detail().name("id");

    type_object->complete().struct_type().member_seq().emplace_back(cst_id);

    CompleteStructMember cst_timeRec;
    cst_timeRec.common().member_id(memberId++);
    cst_timeRec.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_timeRec.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_timeRec.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_timeRec.common().member_flags().IS_OPTIONAL(false);
    cst_timeRec.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_timeRec.common().member_flags().IS_KEY(false);
    cst_timeRec.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_timeRec.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("int64_t", false));

    cst_timeRec.detail().name("timeRec");

    type_object->complete().struct_type().member_seq().emplace_back(cst_timeRec);

    CompleteStructMember cst_timeSent;
    cst_timeSent.common().member_id(memberId++);
    cst_timeSent.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_timeSent.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_timeSent.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_timeSent.common().member_flags().IS_OPTIONAL(false);
    cst_timeSent.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_timeSent.common().member_flags().IS_KEY(false);
    cst_timeSent.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_timeSent.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("int64_t", false));

    cst_timeSent.detail().name("timeSent");

    type_object->complete().struct_type().member_seq().emplace_back(cst_timeSent);


    // Header
    type_object->complete().struct_type().header().detail().type_name("Header");
    // TODO inheritance


    TypeIdentifier identifier;
    identifier._d(EK_COMPLETE);

    SerializedPayload_t payload(static_cast<uint32_t>(
        CompleteStructType::getCdrSerializedSize(type_object->complete().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("Header", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("Header", true);
}
