// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file velocity.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Communication/PacketTypes/velocity.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

Velocity::Velocity()
{
    // m_head com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@687080dc

    // m_magnitude com.eprosima.idl.parser.typecode.PrimitiveTypeCode@7a9273a8
    m_magnitude = 0.0;

}

Velocity::~Velocity()
{


}

Velocity::Velocity(
        const Velocity& x)
{
    m_head = x.m_head;
    m_magnitude = x.m_magnitude;
}

Velocity::Velocity(
        Velocity&& x) noexcept 
{
    m_head = std::move(x.m_head);
    m_magnitude = x.m_magnitude;
}

Velocity& Velocity::operator =(
        const Velocity& x)
{

    m_head = x.m_head;
    m_magnitude = x.m_magnitude;

    return *this;
}

Velocity& Velocity::operator =(
        Velocity&& x) noexcept
{

    m_head = std::move(x.m_head);
    m_magnitude = x.m_magnitude;

    return *this;
}

bool Velocity::operator ==(
        const Velocity& x) const
{

    return (m_head == x.m_head && m_magnitude == x.m_magnitude);
}

bool Velocity::operator !=(
        const Velocity& x) const
{
    return !(*this == x);
}

size_t Velocity::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += Header::getMaxCdrSerializedSize(current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t Velocity::getCdrSerializedSize(
        const Velocity& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += Header::getCdrSerializedSize(data.head(), current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void Velocity::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_head;
    scdr << m_magnitude;

}

void Velocity::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_head;
    dcdr >> m_magnitude;
}

/*!
 * @brief This function copies the value in member head
 * @param _head New value to be copied in member head
 */
void Velocity::head(
        const Header& _head)
{
    m_head = _head;
}

/*!
 * @brief This function moves the value in member head
 * @param _head New value to be moved in member head
 */
void Velocity::head(
        Header&& _head)
{
    m_head = std::move(_head);
}

/*!
 * @brief This function returns a constant reference to member head
 * @return Constant reference to member head
 */
const Header& Velocity::head() const
{
    return m_head;
}

/*!
 * @brief This function returns a reference to member head
 * @return Reference to member head
 */
Header& Velocity::head()
{
    return m_head;
}
/*!
 * @brief This function sets a value in member magnitude
 * @param _magnitude New value for member magnitude
 */
void Velocity::magnitude(
        float _magnitude)
{
    m_magnitude = _magnitude;
}

/*!
 * @brief This function returns the value of member magnitude
 * @return Value of member magnitude
 */
float Velocity::magnitude() const
{
    return m_magnitude;
}

/*!
 * @brief This function returns a reference to member magnitude
 * @return Reference to member magnitude
 */
float& Velocity::magnitude()
{
    return m_magnitude;
}


size_t Velocity::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool Velocity::isKeyDefined()
{
    return false;
}

void Velocity::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
