name: Build Project
run-name: Building Hello World
on: [push]
jobs:
  Compile:
    # TODO: Add Windows and Mac(?) tests
    runs-on: ubuntu-latest
    steps:
      - uses: ouzi-dev/commit-status-updater@v2
        with:
          name: "Compile and Unit Tests"
          status: pending
          url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build project
        run: |
          cd /home/runner/work/SupermileageDisplay/SupermileageDisplay/
          mkdir build
          cd build
          cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE \
          -DCMAKE_BUILD_TYPE:STRING=Debug -G "Unix Makefiles" ..
          cmake --build . --config Debug --target all -j 2 --
      - if: {{ failure() }}
        uses: ouzi-dev/commit-status-updater@v2
        with:
          name: "Compile and Unit Tests"
          status: failure
          url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Run Tests
        run: |
          cd /home/runner/work/SupermileageDisplay/SupermileageDisplay/build/TestApp_artefacts/Debug
          ./SuperMileageDisplay
      - if: {{failure()}}
        uses: ouzi-dev/commit-status-updater@v2
        with:
          name: "Compile and Unit Tests"
          status: failure
          url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
