name: Create docs
run-name: Updating docs
on: [push]
permissions:
        contents: write
jobs:
        report:
                name: Create documentation
                runs-on: ubuntu-latest
                steps:
                        - uses: ouzi-dev/commit-status-updater@v2
                          with:
                                  name: "Generate docs"
                                  status: pending
                                  url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
                        - name: Checkout code
                          uses: actions/checkout@v3
                        - name: Get doxygen
                          run: sudo apt update && sudo apt install doxygen graphviz
                        - name: Run doxygen
                          run: cd /home/runner/work/SupermilageDisplay/SupermilageDisplay && doxygen
                        - name: Push commit
                          run: |
                                  git config --global user.name 'Doc Worker'
                                  git config --global user.email 'Supermileage@cedarville.edu'
                                  git commit -am "Automated doc generation"
                                  git push

